language: generic

services:
 - docker

env:
 - DEPENDENCY_PACKAGES="appstream desktop-file-utils io.elementary.vala-lint meson libgtk-3-dev libgee-0.8-dev valac"

install:
 - docker pull elementary/docker:juno-unstable
 - docker run -v "$PWD":/tmp/build-dir elementary/docker:loki /bin/sh -c "apt-get update && apt-get -y install $DEPENDENCY_PACKAGES && cd /tmp/build-dir && meson build --prefix=/usr && cd build && ninja test"

script:
 - echo BUILDS PASSED
